app:
  name: gopher-app1
  version: 0.1.0
modules:
  core:
    server:
      address: ":8081"
      dashboard:
        enabled: true
        overview:
          app_env: true
          app_debug: true
          app_version: true
          log_level: true
          log_output: true
          trace_sampler: true
          trace_processor: true
      metrics:
        expose: true
        collect:
          enabled: true
        normalize:
          request_path: true
          response_status: true
      healthcheck:
        startup:
          expose: true
        readiness:
          expose: true
        liveness:
          expose: true
      debug:
        config:
          expose: true
        pprof:
          expose: true
        routes:
          expose: true
        stats:
          expose: true
        build:
          expose: true
        modules:
          expose: true
  http:
    server:
      address: ":8080"
      templates:
        enabled: true
        path: templates/*.htm
      trace:
        enabled: true
      metrics:
        collect:
          enabled: true
        normalize:
          request_path: true
          response_status: true
  log:
    level: info
    output: stdout
  trace:
    processor:
      type: noop
  orm:
    driver: postgres                                               # driver to use
    dsn: "postgres:password@tcp(192.168.112.1localhost:5444/)/kk_test"     # database DSN to connect to
    config:
      dry_run: false                                            # disabled by default
      skip_default_transaction: false                           # disabled by default
      full_save_associations: false                             # disabled by default
      prepare_stmt: false                                       # disabled by default
      disable_automatic_ping: false                             # disabled by default
      disable_foreign_key_constraint_when_migrating: false      # disabled by default
      ignore_relationships_when_migrating: false                # disabled by default
      disable_nested_transaction: false                         # disabled by default
      allow_global_update: false                                # disabled by default
      query_fields: false                                       # disabled by default
      translate_error: false                                    # disabled by default