version: '3.9'

services:
  go_dev:
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - go_dev-network
    ports:
      - "8080:8080"
      - "8081:8081"
    expose:
      - "8080"
      - "8081"
    volumes:
      - ../.:/app
    env_file:
      - ../.env

networks:
  go_dev-network:
    driver: bridge